import React, { useState, useEffect, useCallback } from 'react';
import GameCanvas from './components/GameCanvas';
import { GameState, LeaderboardEntry } from './types';
import { createClient } from '@supabase/supabase-js';
import { AlertCircle, CheckCircle2, Copy, ExternalLink, Info, X, Terminal, RefreshCw, Zap } from 'lucide-react';

// Supabase yapılandırması
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

const supabase = (supabaseUrl && supabaseAnonKey) 
  ? createClient(supabaseUrl, supabaseAnonKey) 
  : null;

const App: React.FC = () => {
  const [gameState, setGameState] = useState<GameState>(GameState.LOGIN);
  const [score, setScore] = useState(0);
  const [username, setUsername] = useState('');
  const [leaderboard, setLeaderboard] = useState<LeaderboardEntry[]>([]);
  const [playerRank, setPlayerRank] = useState<number | null>(null);
  const [isSetupModalOpen, setIsSetupModalOpen] = useState(false);
  const [dbStatus, setDbStatus] = useState<'checking' | 'connected' | 'error' | 'no_config'>('checking');
  const [systemLogs, setSystemLogs] = useState<string[]>([]);

  const addLog = (msg: string) => {
    setSystemLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`].slice(-5));
  };

  const checkConnection = useCallback(async () => {
    setDbStatus('checking');
    addLog("Sistem kontrolü başlatıldı...");

    if (!supabaseUrl || !supabaseAnonKey) {
      addLog("HATA: Ortam değişkenleri (ENV) bulunamadı.");
      setDbStatus('no_config');
      return;
    }

    addLog("Supabase istemcisi hazırlandı.");
    
    try {
      if (!supabase) throw new Error("Client initialization failed");
      
      const { error } = await supabase.from('leaderboard').select('count').limit(1);
      
      if (error) {
        addLog(`HATA: Tablo erişimi reddedildi (${error.code})`);
        throw error;
      }
      
      addLog("Bağlantı başarılı! Tablo erişilebilir.");
      setDbStatus('connected');
    } catch (err: any) {
      addLog(`KRİTİK HATA: ${err.message || "Bilinmeyen hata"}`);
      setDbStatus('error');
    }
  }, []);

  const fetchLeaderboard = useCallback(async () => {
    if (!supabase || dbStatus !== 'connected') return;
    try {
      const { data, error } = await supabase
        .from('leaderboard')
        .select('username, score')
        .order('score', { ascending: false })
        .limit(10);
      if (error) throw error;
      if (data) setLeaderboard(data);
    } catch (err) {
      addLog("Liderlik tablosu güncellenemedi.");
    }
  }, [dbStatus]);

  useEffect(() => {
    checkConnection();
  }, [checkConnection]);

  useEffect(() => {
    const savedUser = localStorage.getItem('nehir-akincisi-user');
    if (savedUser) {
      setUsername(savedUser);
      setGameState(GameState.MENU);
      fetchLeaderboard();
    }
  }, [fetchLeaderboard]);

  const handleLogin = (name: string) => {
    if (name.length >= 3 && name.length <= 12) {
      const sanitized = name.toUpperCase().replace(/[^A-Z0-9]/g, '');
      setUsername(sanitized);
      localStorage.setItem('nehir-akincisi-user', sanitized);
      setGameState(GameState.MENU);
      fetchLeaderboard();
    }
  };

  const saveScoreToSupabase = useCallback(async (finalScore: number) => {
    if (!supabase || dbStatus !== 'connected' || !username || finalScore <= 0) return;
    try {
      await supabase.from('leaderboard').insert([{ username, score: finalScore }]);
      const { count } = await supabase.from('leaderboard').select('*', { count: 'exact', head: true }).gt('score', finalScore);
      if (count !== null) setPlayerRank(count + 1);
      fetchLeaderboard();
    } catch (err) {
      addLog("Skor kaydedilirken hata oluştu.");
    }
  }, [username, fetchLeaderboard, dbStatus]);

  useEffect(() => {
    if (gameState === GameState.GAME_OVER) saveScoreToSupabase(score);
    if (gameState === GameState.MENU) fetchLeaderboard();
  }, [gameState, score, fetchLeaderboard, saveScoreToSupabase]);

  const copySql = () => {
    const sql = `-- Supabase SQL Editor:
create table leaderboard (
  id bigint generated by default as identity primary key,
  username text not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table leaderboard enable row level security;
create policy "Herkes skor ekleyebilir" on leaderboard for insert with check (true);
create policy "Herkes skorları görebilir" on leaderboard for select using (true);`;
    navigator.clipboard.writeText(sql);
    alert("SQL Kodu kopyalandı!");
  };

  return (
    <div className="w-full h-screen flex flex-col items-center justify-center bg-gray-950 p-0 md:p-4 lg:p-8">
      
      <div className="w-full max-w-lg h-full max-h-[900px] bg-black rounded-xl overflow-hidden shadow-2xl relative border-4 border-gray-800 ring-4 ring-black crt-overlay">
        <div className="absolute inset-0 pointer-events-none z-50 bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.1)_50%),linear-gradient(90deg,rgba(255,0,0,0.03),rgba(0,255,0,0.01),rgba(0,0,255,0.03))] bg-[length:100%_4px,3px_100%]"></div>
        
        <GameCanvas 
          gameState={gameState} 
          setGameState={setGameState}
          score={score}
          setScore={setScore}
          highScore={0}
          username={username}
          leaderboard={leaderboard}
          playerRank={playerRank}
          onLogin={handleLogin}
        />
        
        {/* Durum Çubuğu */}
        <div className="absolute bottom-1 left-0 right-0 px-4 flex justify-between items-center text-[10px] text-gray-500 font-mono z-20 bg-black/40 backdrop-blur-sm">
           <div className="flex items-center gap-2">
             <Terminal size={10} />
             <span>PILOT: {username || 'ANONYMOUS'}</span>
           </div>
           <button 
             onClick={() => setIsSetupModalOpen(true)}
             className={`flex items-center gap-1 px-2 py-1 transition-all rounded ${
               dbStatus === 'connected' ? 'text-green-500 hover:bg-green-500/10' : 
               dbStatus === 'no_config' ? 'text-yellow-500 hover:bg-yellow-500/10' : 
               'text-red-500 hover:bg-red-500/10'
             }`}
           >
             <div className={`w-1.5 h-1.5 rounded-full animate-pulse ${
               dbStatus === 'connected' ? 'bg-green-500' : 
               dbStatus === 'no_config' ? 'bg-yellow-500' : 'bg-red-500'
             }`} />
             {dbStatus === 'connected' ? 'SYSTEM_ONLINE' : 'SYSTEM_OFFLINE'}
             <Info size={10} />
           </button>
        </div>
      </div>

      {/* BIOS / Diagnostic Modal */}
      {isSetupModalOpen && (
        <div className="fixed inset-0 bg-black/90 backdrop-blur-xl z-[100] flex items-center justify-center p-4">
          <div className="bg-gray-900 border-2 border-green-900/30 w-full max-w-md rounded-lg shadow-[0_0_50px_rgba(0,255,0,0.1)] overflow-hidden flex flex-col max-h-[90vh]">
            <div className="p-4 border-b border-green-900/20 flex justify-between items-center bg-black/50">
              <div className="flex items-center gap-2 text-green-500">
                <Terminal size={16} />
                <h3 className="pixel-font text-[10px]">BIOS_v2.5_DIAGNOSTICS</h3>
              </div>
              <button onClick={() => setIsSetupModalOpen(false)} className="text-gray-500 hover:text-white transition-colors">
                <X size={20} />
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto space-y-6 font-mono">
              {/* BIOS Info */}
              <div className="text-[10px] text-green-800 space-y-1 border-l-2 border-green-900/30 pl-3">
                <p>CPU: GEMINI_RIVER_AKINCI_V2</p>
                <p>MEMORY: 640KB OK</p>
                <p>STORAGE: SUPABASE_CLOUD_LINK</p>
              </div>

              {/* Status Table */}
              <div className="space-y-2">
                <div className="flex items-center justify-between p-2 bg-black/40 border border-green-900/10 rounded">
                  <span className="text-xs text-gray-500">ENV_URL</span>
                  {supabaseUrl ? <span className="text-green-500 text-[10px]">LOADED</span> : <span className="text-red-500 text-[10px]">MISSING</span>}
                </div>
                <div className="flex items-center justify-between p-2 bg-black/40 border border-green-900/10 rounded">
                  <span className="text-xs text-gray-500">ENV_KEY</span>
                  {supabaseAnonKey ? <span className="text-green-500 text-[10px]">LOADED</span> : <span className="text-red-500 text-[10px]">MISSING</span>}
                </div>
                <div className="flex items-center justify-between p-2 bg-black/40 border border-green-900/10 rounded">
                  <span className="text-xs text-gray-500">CONNECTION</span>
                  <span className={`${dbStatus === 'connected' ? 'text-green-500' : 'text-red-500'} text-[10px]`}>{dbStatus.toUpperCase()}</span>
                </div>
              </div>

              {/* Logs */}
              <div className="bg-black p-3 rounded border border-green-900/20 h-32 overflow-hidden flex flex-col justify-end">
                <div className="text-[9px] text-green-600 space-y-1 opacity-80">
                  {systemLogs.map((log, i) => (
                    <div key={i} className="flex gap-2">
                      <span className="text-green-900 shrink-0">&gt;</span>
                      <span className="break-all">{log}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Action UI */}
              <div className="space-y-3">
                {dbStatus === 'no_config' && (
                  <div className="bg-yellow-900/20 p-4 border border-yellow-900/40 rounded text-yellow-200">
                    <h4 className="text-xs font-bold mb-2 flex items-center gap-2"><Zap size={14} className="text-yellow-500" /> ÖNEMLİ ADIM!</h4>
                    <p className="text-[10px] leading-relaxed">
                      Değişkenleri Vercel'e eklediyseniz, bu değişikliklerin aktif olması için <b>projenizi Vercel üzerinden tekrar "Deploy" etmelisiniz.</b> Sadece kaydetmek kodun güncellenmesini sağlamaz.
                    </p>
                  </div>
                )}

                <div className="grid grid-cols-2 gap-2">
                  <button 
                    onClick={checkConnection}
                    className="py-3 bg-green-900/20 hover:bg-green-900/40 text-green-500 text-[10px] border border-green-900/40 rounded flex items-center justify-center gap-2 transition-all"
                  >
                    <RefreshCw size={12} /> SİSTEMİ YENİLE
                  </button>
                  <button 
                    onClick={copySql}
                    className="py-3 bg-blue-900/20 hover:bg-blue-900/40 text-blue-500 text-[10px] border border-blue-900/40 rounded flex items-center justify-center gap-2 transition-all"
                  >
                    <Copy size={12} /> SQL KOPYALA
                  </button>
                </div>
                
                <a 
                  href="https://vercel.com" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="w-full py-3 bg-white/5 hover:bg-white/10 text-white text-[10px] border border-white/10 rounded flex items-center justify-center gap-2 transition-all"
                >
                  <ExternalLink size={12} /> VERCEL DASHBOARD
                </a>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default App;