import React, { useState, useEffect, useCallback } from 'react';
import GameCanvas from './components/GameCanvas';
import { GameState, LeaderboardEntry } from './types';
import { createClient } from '@supabase/supabase-js';
import { AlertCircle, CheckCircle2, Copy, ExternalLink, Info, X } from 'lucide-react';

// Supabase yapılandırması
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

const supabase = (supabaseUrl && supabaseAnonKey) 
  ? createClient(supabaseUrl, supabaseAnonKey) 
  : null;

const App: React.FC = () => {
  const [gameState, setGameState] = useState<GameState>(GameState.LOGIN);
  const [score, setScore] = useState(0);
  const [username, setUsername] = useState('');
  const [leaderboard, setLeaderboard] = useState<LeaderboardEntry[]>([]);
  const [playerRank, setPlayerRank] = useState<number | null>(null);
  const [isSetupModalOpen, setIsSetupModalOpen] = useState(false);
  const [dbStatus, setDbStatus] = useState<'checking' | 'connected' | 'error' | 'no_config'>('checking');

  const checkConnection = useCallback(async () => {
    if (!supabase) {
      setDbStatus('no_config');
      return;
    }
    try {
      const { error } = await supabase.from('leaderboard').select('count').limit(1);
      if (error) throw error;
      setDbStatus('connected');
    } catch (err) {
      console.error("DB Connection Error:", err);
      setDbStatus('error');
    }
  }, []);

  const fetchLeaderboard = useCallback(async () => {
    if (!supabase || dbStatus !== 'connected') return;
    try {
      const { data, error } = await supabase
        .from('leaderboard')
        .select('username, score')
        .order('score', { ascending: false })
        .limit(10);
      if (error) throw error;
      if (data) setLeaderboard(data);
    } catch (err) {
      setDbStatus('error');
    }
  }, [dbStatus]);

  useEffect(() => {
    checkConnection();
  }, [checkConnection]);

  useEffect(() => {
    const savedUser = localStorage.getItem('nehir-akincisi-user');
    if (savedUser) {
      setUsername(savedUser);
      setGameState(GameState.MENU);
      fetchLeaderboard();
    }
  }, [fetchLeaderboard]);

  const handleLogin = (name: string) => {
    if (name.length >= 3 && name.length <= 12) {
      const sanitized = name.toUpperCase().replace(/[^A-Z0-9]/g, '');
      setUsername(sanitized);
      localStorage.setItem('nehir-akincisi-user', sanitized);
      setGameState(GameState.MENU);
      fetchLeaderboard();
    }
  };

  const saveScoreToSupabase = useCallback(async (finalScore: number) => {
    if (!supabase || dbStatus !== 'connected' || !username || finalScore <= 0) return;
    try {
      await supabase.from('leaderboard').insert([{ username, score: finalScore }]);
      const { count } = await supabase.from('leaderboard').select('*', { count: 'exact', head: true }).gt('score', finalScore);
      if (count !== null) setPlayerRank(count + 1);
      fetchLeaderboard();
    } catch (err) {
      console.error("Score save error:", err);
    }
  }, [username, fetchLeaderboard, dbStatus]);

  useEffect(() => {
    if (gameState === GameState.GAME_OVER) saveScoreToSupabase(score);
    if (gameState === GameState.MENU) fetchLeaderboard();
  }, [gameState, score, fetchLeaderboard, saveScoreToSupabase]);

  const copySql = () => {
    const sql = `-- Supabase SQL Editor için gerekli kodlar:
create table leaderboard (
  id bigint generated by default as identity primary key,
  username text not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table leaderboard enable row level security;
create policy "Herkes skor ekleyebilir" on leaderboard for insert with check (true);
create policy "Herkes skorları görebilir" on leaderboard for select using (true);`;
    navigator.clipboard.writeText(sql);
    alert("SQL Kodu kopyalandı!");
  };

  return (
    <div className="w-full h-screen flex flex-col items-center justify-center bg-gray-950 p-0 md:p-4 lg:p-8">
      
      <div className="w-full max-w-lg h-full max-h-[900px] bg-black rounded-xl overflow-hidden shadow-2xl relative border-4 border-gray-800 ring-4 ring-black crt-overlay">
        <div className="absolute inset-0 pointer-events-none z-50 bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.1)_50%),linear-gradient(90deg,rgba(255,0,0,0.03),rgba(0,255,0,0.01),rgba(0,0,255,0.03))] bg-[length:100%_4px,3px_100%]"></div>
        
        <GameCanvas 
          gameState={gameState} 
          setGameState={setGameState}
          score={score}
          setScore={setScore}
          highScore={0}
          username={username}
          leaderboard={leaderboard}
          playerRank={playerRank}
          onLogin={handleLogin}
        />
        
        {/* Bağlantı Durum Çubuğu */}
        <div className="absolute bottom-1 left-0 right-0 px-4 flex justify-between items-center text-[10px] text-gray-500 font-mono z-20">
           <div>PILOT: {username || 'NOT_LOGGED_IN'}</div>
           <button 
             onClick={() => setIsSetupModalOpen(true)}
             className={`flex items-center gap-1 px-2 py-0.5 rounded transition ${
               dbStatus === 'connected' ? 'text-green-500 hover:bg-green-500/10' : 
               dbStatus === 'no_config' ? 'text-yellow-500 hover:bg-yellow-500/10 animate-pulse' : 
               'text-red-500 hover:bg-red-500/10 animate-pulse'
             }`}
           >
             <div className={`w-1.5 h-1.5 rounded-full ${
               dbStatus === 'connected' ? 'bg-green-500' : 
               dbStatus === 'no_config' ? 'bg-yellow-500' : 'bg-red-500'
             }`} />
             {dbStatus === 'connected' ? 'DB_ONLINE' : dbStatus === 'no_config' ? 'CONFIG_MISSING' : 'DB_ERROR'}
             <Info size={10} />
           </button>
        </div>
      </div>

      {/* Kurulum / Teşhis Modalı */}
      {isSetupModalOpen && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-[100] flex items-center justify-center p-4">
          <div className="bg-gray-900 border-2 border-gray-800 w-full max-w-md rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
            <div className="p-4 border-b border-gray-800 flex justify-between items-center bg-gray-800/50">
              <h3 className="pixel-font text-xs text-white">SYSTEM_DIAGNOSTICS</h3>
              <button onClick={() => setIsSetupModalOpen(false)} className="text-gray-400 hover:text-white"><X size={20} /></button>
            </div>
            
            <div className="p-6 overflow-y-auto space-y-6">
              {/* Durum Özeti */}
              <div className="space-y-3">
                <div className="flex items-center justify-between p-3 bg-black/40 rounded-lg border border-gray-800">
                  <span className="text-xs font-mono text-gray-400">SUPABASE_URL</span>
                  {supabaseUrl ? <CheckCircle2 size={16} className="text-green-500" /> : <AlertCircle size={16} className="text-red-500" />}
                </div>
                <div className="flex items-center justify-between p-3 bg-black/40 rounded-lg border border-gray-800">
                  <span className="text-xs font-mono text-gray-400">SUPABASE_ANON_KEY</span>
                  {supabaseAnonKey ? <CheckCircle2 size={16} className="text-green-500" /> : <AlertCircle size={16} className="text-red-500" />}
                </div>
                <div className="flex items-center justify-between p-3 bg-black/40 rounded-lg border border-gray-800">
                  <span className="text-xs font-mono text-gray-400">TABLE_ACCESSIBILITY</span>
                  {dbStatus === 'connected' ? <CheckCircle2 size={16} className="text-green-500" /> : <AlertCircle size={16} className="text-red-500" />}
                </div>
              </div>

              {/* Hata Mesajı ve Çözüm */}
              {dbStatus !== 'connected' && (
                <div className="space-y-4">
                  <div className="bg-blue-900/20 p-4 rounded-xl border border-blue-900/50">
                    <h4 className="text-blue-400 font-bold text-sm mb-2 flex items-center gap-2"><Info size={16} /> Kurulum Adımları</h4>
                    <ol className="text-xs text-blue-200/80 space-y-2 list-decimal ml-4">
                      <li>Vercel projenizde <b>Environment Variables</b> ayarlarına gidin.</li>
                      <li><code className="bg-black/40 px-1 rounded text-white">SUPABASE_URL</code> ve <code className="bg-black/40 px-1 rounded text-white">SUPABASE_ANON_KEY</code> ekleyin.</li>
                      <li>Supabase <b>SQL Editor</b> kısmına aşağıdaki kodu yapıştırıp "Run" butonuna basın:</li>
                    </ol>
                  </div>

                  <button 
                    onClick={copySql}
                    className="w-full py-3 bg-gray-800 hover:bg-gray-700 text-white rounded-lg flex items-center justify-center gap-2 text-xs font-mono transition"
                  >
                    <Copy size={14} /> SQL KODUNU KOPYALA
                  </button>
                  
                  <a 
                    href="https://supabase.com/dashboard" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="w-full py-3 bg-green-900/40 hover:bg-green-900/60 text-green-400 rounded-lg flex items-center justify-center gap-2 text-xs font-mono transition border border-green-900/50"
                  >
                    <ExternalLink size={14} /> SUPABASE DASHBOARD AÇ
                  </a>
                </div>
              )}

              {dbStatus === 'connected' && (
                <div className="text-center py-4">
                  <div className="w-12 h-12 bg-green-500/20 rounded-full flex items-center justify-center mx-auto mb-3">
                    <CheckCircle2 className="text-green-500" size={24} />
                  </div>
                  <p className="text-xs text-green-400 font-mono">HER ŞEY YOLUNDA! SISTEM ÇEVRİMİÇİ.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default App;